# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFnNSGnEe3OXdSzDM-kmziGtmXcpkeE-
"""

# Restaurant Ordering System

orders = []

while True:
    print("\n===== RESTAURANT ORDERING SYSTEM =====")
    print("1. Add Order")
    print("2. View Orders")
    print("3. Search Order")
    print("4. Update Order Status")
    print("5. Calculate Total Sales")
    print("6. Count Completed Orders")
    print("7. Exit")

    choice = input("Enter your choice (1-7): ")

    if choice == "1":
        order_id = input("Enter Order ID: ")
        customer_name = input("Enter Customer Name: ")
        food_item = input("Enter Food Item: ")
        amount = float(input("Enter Amount: "))

        order = {
            "Order ID": order_id,
            "Customer Name": customer_name,
            "Food Item": food_item,
            "Amount": amount,
            "Status": "Pending"
        }

        orders.append(order)
        print("Order added successfully!")

    elif choice == "2":
        if len(orders) == 0:
            print("No orders available.")
        else:
            print("\n--- Order List ---")
            for order in orders:
                print(f"Order ID: {order['Order ID']}")
                print(f"Customer Name: {order['Customer Name']}")
                print(f"Food Item: {order['Food Item']}")
                print(f"Amount: Rs. {order['Amount']}")
                print(f"Status: {order['Status']}")
                print("-" * 30)

    elif choice == "3":
        search_id = input("Enter Order ID to search: ")
        found = False

        for order in orders:
            if order["Order ID"] == search_id:
                print("\nOrder Found!")
                print(f"Customer Name: {order['Customer Name']}")
                print(f"Food Item: {order['Food Item']}")
                print(f"Amount: Rs. {order['Amount']}")
                print(f"Status: {order['Status']}")
                found = True
                break

        if not found:
            print("Order not found.")

    elif choice == "4":
        update_id = input("Enter Order ID to update: ")
        found = False

        for order in orders:
            if order["Order ID"] == update_id:
                print(f"Current Status: {order['Status']}")
                new_status = input("Enter new status (Pending/Completed): ")

                if new_status.lower() == "pending":
                    order["Status"] = "Pending"
                elif new_status.lower() == "completed":
                    order["Status"] = "Completed"
                else:
                    print("Invalid status!")
                    break

                print("Order status updated successfully!")
                found = True
                break

        if not found:
            print("Order not found.")

    elif choice == "5":
        total_sales = 0

        for order in orders:
            total_sales += order["Amount"]

        print(f"Total Sales: Rs. {total_sales}")

    elif choice == "6":
        completed_count = 0

        for order in orders:
            if order["Status"] == "Completed":
                completed_count += 1

        print(f"Completed Orders: {completed_count}")

    elif choice == "7":
        print("Thank you for using the Restaurant Ordering System!")
        break

    else:
        print("Invalid choice! Please enter a number between 1 and 7.")